pipeline { 
   agent {label 'terraform'} 
     stages { 
     	stage('Install_terraform') {
		steps {
		    script {
			def tfExisits = fileExists '/usr/bin/terraform'
			if (tfExisits) {
			   echo "Terraform package already exisit hence skipping the installation and setup process..."
			   echo "Distroying any old tf files if exist"
			   sh "sudo rm -rf *.tf*"	
			   sh "sudo rm -rf terraform*"	
			}else{
			sh "cd /tmp"
			sh "curl -o terraform.zip https://releases.hashicorp.com/terraform/0.12.8/terraform_0.12.8_linux_amd64.zip"
			sh "unzip terraform.zip"
			sh "sudo mv terraform /usr/bin"
			sh "sudo rm -rf terraform.zip"
			sh "sudo rm -rf *.tf*"
			sh "sudo rm -rf Terraform*"
			}
		    }
		}
	    }
	stage('Clone Cookbook from Git') {
            steps {
                sh "git clone https://github.com/Abhishek247/Terraform-pipeline1.git"
		sh "ls -al"
            }
        }
	stage('Invoke Terraform init'){
	    steps{
		sh "cd $WORKSPACE/dev ; terraform init"
	    }
	}
	stage('Invoke Terraform plan'){
            steps{
                sh "cd $WORKSPACE/dev ; terraform plan -out terraform.tfplan"
            }
        }
    }
}
